# Generated by Django 4.0.5 on 2022-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
